version: "3.9"

services:
  ssh:
    build: ./ssh
    container_name: ${VPNName}
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
    ports:
      - "${VPNPort}:${VPNPort}"
    entrypoint: /start_ssh.sh
    hostname: ${VPNName}
    networks:
      streetshares_network:
        ipv4_address: ${VPNIP}
  ldap:
    build: ./ldap
    environment:
       LDAPIP: ${LDAPIP}
       LDAP_ORGANISATION: ${LDAP_ORGANISATION}
       LDAP_DOMAIN: ${LDAP_DOMAIN}
       LDAP_BASE_DN: ${LDAP_BASE_DN}
       LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
       LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
       LDAP_READONLY_USER: ${LDAP_READONLY_USER}
       LDAPIP: ${LDAPIP}
    container_name: ${LDAPName}
    hostname: ${LDAPName}
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
    networks:
      streetshares_network:
        ipv4_address: ${LDAPIP}
# the LDAP server automatically run process.sh which is a LDAP file
  rsyslog:
    build: ./rsyslog
    container_name: ${RsyslogName}
    hostname: ${RsyslogName}
    networks:
      streetshares_network:
        ipv4_address: ${RsyslogIP}
  web:
    build: ./web
    container_name: ${WebName}
    hostname: ${WebName}
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
    entrypoint: /start_web.sh
    ports:
      - "443:443"
    networks:
      streetshares_network:
        ipv4_address: ${WebIP}
  Station_Automation:
    build: ./client.credit-information
    environment:
       LDAPIP: ${LDAPIP}
       LDAP_BASE_DN: ${LDAP_BASE_DN}
       LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    container_name: ${SSHName}
    hostname: ${SSHName}
    entrypoint: /start_ssh.sh
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
    networks:
      streetshares_network:
        ipv4_address: ${SSHIP}
  snort:
    build: ./snort
    network_mode: "host"
    container_name: ${SNORTName}
    hostname: ${SNORTName}
    entrypoint: /start_snort.sh
    volumes:
      - ./rsyslog.conf:/etc/rsyslog.conf
networks:
  streetshares_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NetworkSubnet}
          gateway: ${Gateway}
